### ISSUE TITLE
Specific dependencies

### ISSUE THREAD

**Issue by jdossgollin** [Project-Platypus/Rhodium#27] opened 2020-05-05 20:56 UTC
I have been helping a student run the Eijgenraam example and built a conda environment to install required packages. It's available at https://github.com/jdossgollin/conda-envs/blob/master/environments/rhodium.yml.

First I tried running python 3.6, but ran into an issue with the `comb` function in `scipy`, which has moved from `scipy.misc` to `scipy.special`. If there are specific versions of scipy needed, that should be reflected in `requirements.txt` and `setup.py`. Now I can get anything running, but can't plot anything because I get an `AttributeError: module 'matplotlib.colors' has no attribute 'to_rgba'`. This seems to be another version issue.

It would be really helpful for me to develop the above conda environment so that it "just works" can be used for teaching.

**Comment by NLaws** [comment] 2020-09-10 23:54
I'm having a similar issue with dependencies, and it looks like others have made other, related Issues on this topic. My specific issue is `ModuleNotFoundError: No module named 'sklearn.externals.six'` from `Rhodium/rhodium/classification.py`. Looking at the requirements.txt in Rhodium there is no version of sklearn specified.  This could perhaps be fixed if one of the developers ran `pip freeze > requirements.txt` in a working environment.

**Comment by dhadka** [comment] 2022-11-22 01:52
This should be fixed after updating to pyproject.toml.  Also have GitHub Actions testing to pick up any regressions.

**Closed by dhadka** 2022-11-22 01:52 UTC
